apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-redirections
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: httpd
      release: {{ .Release.Name }}
