apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redirections
spec:
  ports:
  - name: httpd
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: httpd
    release: {{ .Release.Name }}
  type: ClusterIP
