ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hosts:
  - host1
  - host2    

redirections: |
  # Enable this only during debuging of rewrite rules !
  #LogLevel alert rewrite:trace5
  RewriteCond %{HTTP_HOST} =trainings.company.tld
  RewriteRule ^.*$ https://company.tld/trainings [R=301,L]
