apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  WORDPRESS_ADMIN_USER: {{ .Values.wordpress.admin.username }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.wordpress.admin.email }}
  WORDPRESS_DB_HOST: "{{ template "mysql_host" . }}"
  WORDPRESS_DB_NAME: {{ required "Missing value mysql.auth.database" .Values.mysql.auth.database }}
  WORDPRESS_DB_USER: {{ required "Missing value mysql.auth.username" .Values.mysql.auth.username }}
  WORDPRESS_DESCRIPTION: "{{ .Values.wordpress.description }}"
  WORDPRESS_PERMALINK_STRUCTURE: "{{ .Values.wordpress.permalink_structure }}"
  WORDPRESS_RSS_URL: "{{ .Values.wordpress.rss_url }}"
  WORDPRESS_TITLE: "{{ .Values.wordpress.title }}"
  NEXT_PUBLIC_WORDPRESS_URL: "https://{{ template "next_public_wordpress_domain" . }}"
  NEXT_PRIVATE_WORDPRESS_URL: "{{ template "next_private_wordpress_url" . }}"
  NEXT_TELEMETRY_DISABLED: "1"
  WORDPRESS_FRONT_URL: "https://{{ template "wordpress_front_domain" . }}"
  MIGRATEDB_LICENSE: ""
  MIGRATEDB_FROM: ""
  API_URL: "{{ template "api_url" . }}"
  VERCEL_DEPLOY_URL: "{{ .Values.vercel.deploy_url }}"
  {{- if .Values.varnish.enabled }}
  VARNISH_KUBERNETES_HEADLESS_SERVICE: "{{ .Release.Name }}-varnish-purge"
  VARNISH_KUBERNETES_STATEFULSET_NAME: "{{ .Release.Name }}-varnish"
  VARNISH_PORT: "{{ .Values.varnish.service.port }}"
  VARNISH_PURGE_AUTHORIZATION: "{{ .Values.varnish.purge.authorization }}"
  {{- end }}
