{{- if .Values.wordpress.ingress.enabled -}}
{{- $svcPort := .Values.wordpress.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-wordpress
  {{- with .Values.wordpress.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ template "next_public_wordpress_domain" . }}
    secretName: {{ .Release.Name }}-wordpress-tls
  rules:
    - host: {{ template "next_public_wordpress_domain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-wordpress
                port:
                  number: {{ $svcPort }}
{{- end }}
