{{- if .Values.networkPolicy.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny-ingress
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
{{- end }}
