{{- if .Values.networkPolicy.enabled }}
{{- if .Values.varnish.enabled }}
kind: NetworkPolicy
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
metadata:
  name: {{ .Release.Name }}-varnish
  labels:
    release: {{ .Release.Name }}
    app: varnish
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
      app: varnish
  ingress:
    # Allow inbound connections
    - ports:
      - port: {{ .Values.varnish.service.port }}
      from:
      - podSelector:
          matchLabels:
            release: {{ .Release.Name }}
            app: wordpress
      {{- range .Values.networkPolicy.namespaceSelectors }}
      - podSelector: {}
        namespaceSelector:
          matchLabels:
          {{- toYaml . | nindent 12 }}
      {{- end }}  
{{- end }}
{{- end }}
