{{- if .Values.wordpress.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
spec:
  storageClassName: "regionalpd-sc-euwest1"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
{{- end }}
