apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.wordpress.admin.password | b64enc }}
  NEXT_VALIDATION_TOKEN: {{ .Values.next_validation_token | b64enc }}
