{{- if .Values.varnish.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-varnish
  labels:
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.varnish.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    release: "{{ .Release.Name }}"
    app: varnish
{{- end }}
