vercel:
  # deploy url : vercel webhook called by wordpress to redeploy node app (purge cache)
  deploy_url: ""

frontend:
  enabled: false
  replicaCount: 1
  
  image:
    repository: "your_repo/your_path/frontend"
    pullPolicy: IfNotPresent
    tag: "your_tag"
  
  podAnnotations: {}
  
  service:
    type: ClusterIP
    port: 3000
  
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
    ingressClassName: nginx

    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  

wordpress:
  replicaCount: 1

  pdb:
    maxUnavailable: 1
  
  image:
    repository: "your_repo/your_path/frontend"
    pullPolicy: IfNotPresent
    tag: "your_tag"

  admin:
    username: "change_me"
    password: "change_me"
    email: "change_me@change_me"
  description: ""
  permalink_structure: "/%year%/%monthnum%/%day%/%postname%/"
  title: "change_me"
  
  podAnnotations: {}
  
  service:
    type: ClusterIP
    port: 8080
  
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
    ingressClassName: nginx

    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  
  resources: {}
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistence:
    enabled: true
    size: 1Gi
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  rss_url: ""

mysql:
  enabled: false
  auth:
    username: "change_me"
    password: "change_me"
    database: "change_me"
    rootPassword: "change_me"
  external_host: "your_external_database_ip"

varnish:
  enabled: false
  replicaCount: 1
  image:
    repository: "your_repo/your_path/varnish"
    pullPolicy: IfNotPresent
    tag: "your_tag"

  purge:
    # Update with "Basic random_base64"
    authorization: "change me"

  service:
    type: ClusterIP
    port: 80

  # always ensure memory request is enough for cacheSize
  cacheSize: "20M"
  resources:
    requests:
      #cpu: 100m
      memory: 30Mi
    limits: {}
      #cpu: 100m
      #memory: 128Mi

site_front_domain: chart-example.local
site_back_domain: api.chart-example.local

networkPolicy:
  enabled: true
  # List of namespaces to allow, based on their labels
  namespaceSelectors:
  - service: ingress
  - service: monitoring
    #other_label: value
