{{ if .Values.postgresql.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
{{- end }}
