apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-spa
  labels:
    app: spa
    release: {{ .Release.Name }}
  annotations:
    {{ toYaml .Values.ingresses.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingresses.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.dns_suffix }}
      secretName: spa
  rules:
    - host: {{ .Values.dns_suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-spa
                port:
                  number: 80
