apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt
data:
  JWT_PUBLIC_KEY: {{ .Values.api.jwt.public_key | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.api.jwt.secret_key | b64enc | quote }}
  JWT_PASSPHRASE: {{ .Values.api.jwt.passphrase | b64enc | quote }}
